app: web
debug: true
db:
  switch: false
  picture:
    dialect: mysql
    dsn: root:123456@tcp(127.0.0.1:3306)/picture?charset=utf8mb4&parseTime=True&loc=Local
  poetry:
    dialect: mysql
    dsn: root:123456@tcp(127.0.0.1:3306)/poetry?charset=utf8mb4&parseTime=True&loc=Local
redis:
  switch: false
  clients:
    web:
      addrs:
        - 127.0.0.1:6379
      db: 0
      password:
      type: single-node
  default: default
log:
  outputs:
    - stdout
    - ./logs/api.log
elasticsearch:
  switch: false
  engine:
    chinese_indices: chinese.book.student.alias
    addresses:
      - http://127.0.0.1:9200
    username: admin
    password: 123456
rabbitmq:
  switch: false
  engine:
    addresses: localhost:5672/
    username: myuser
    password: mypass
    queue-name: order
cron:
  switch: false
http:
  switch: false
wechat:
  appid: "****"
  secret: "****"
  mch-id: "***"
  mch-cert: "***"
  mch-iv3: "***"